CREATE TABLE Armarios(
    id INT IDENTITY(1,1) PRIMARY KEY,
    TIPO VARCHAR(10) NOT NULL,  -- GAVETAS OU PORTAS
    DIVISOES INT NOT NULL,
    NUMERO INT NOT NULL,
);
CREATE TABLE Gavetas(
    id INT IDENTITY(1,1) PRIMARY KEY,
    NOME CHAR(1) NOT NULL,
    CONTEUDO VARCHAR(30) NOT NULL,
    ID_ARMARIO INT,
    FOREIGN KEY (ID_ARMARIO) REFERENCES Armarios(id)
);
CREATE TABLE Compartimentos(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NUMERO int,
    ID_GAVETA INT,
    FOREIGN KEY (ID_GAVETA) REFERENCES Gavetas(id)
);
CREATE TABLE Tipos_de_ferramentas(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NOME VARCHAR(30)
);
CREATE TABLE Ferramentas(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    OBS VARCHAR(70) NOT NULL,
    STATUS VARCHAR(30) NOT NULL,
    ID_TIPO INT NOT NULL,
    ID_COMPARTIMENTO INT NOT NULL,
    ID_GAVETA INT NOT NULL,
    ID_ARMARIO INT NOT NULL,
    FOREIGN KEY (ID_TIPO) REFERENCES Tipos_de_ferramentas(ID),
    FOREIGN KEY (ID_COMPARTIMENTO) REFERENCES Compartimentos(ID),
    FOREIGN KEY (ID_GAVETA) REFERENCES Gavetas(ID),
    FOREIGN KEY (ID_ARMARIO) REFERENCES Armarios(ID),
);
-- DROP TABLE Armarios
-- DROP TABLE Gavetas
-- DROP TABLE Compartimentos
-- DROP TABLE Tipos_de_ferramentas
-- DROP TABLE Ferramentas

select * from Armarios
select * from Gavetas
SELECT * from Compartimentos
SELECT * FROM Tipos_de_ferramentas
SELECT * FROM Ferramentas
INSERT Ferramentas VALUES ('BROCA 10mm', 'NOVA','DISPONIVEL', 1, 1, 1, 1)

SELECT COUNT(*) FROM Ferramentas WHERE  (NOME = 'BROCA 10mm')